name: HUHUU!

on:
  push:
    branches:
      - master

jobs:
  huhuu_job:
    runs-on: ubuntu-18.04
    steps: 
      - name: Say HUHUU
        run: echo "HUHUU!!!"
      - name: Print date
        run: date
      - name: List files
        run: ls -l